name: Continuous Integration

on:
  push:
    branches: [main]
    paths: ["**.cpp"]

  pull_request:
    branches: [main]
    paths: ["**.cpp"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Zig
        uses: goto-bus-stop/setup-zig@v2

      - name: Build executables
        run: |
          zig env
          zig build exes
